apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: fedcat
  name: fedcat-neo4j-data-volume
  labels:
    app: fc-service
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared-data/neo4j
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fedcat
  name: fedcat-neo4j-data-claim
  labels:
    app: fc-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi