version: '3.7'

services:
  postgres:
    container_name: "postgres"
    image: library/postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_MULTIPLE_DATABASES: fed_cat, keycloak
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - "gaia-x"
    volumes:
#      - pgdata:/var/lib/postgresql/data/
      - ./postgres-initdb-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 256M

  keycloak:
    container_name: "keycloak"
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
      PROXY_ADDRESS_FORWARDING: "true"
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: unless-stopped
    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms:/opt/keycloak/data/import"
    command: >
      start --db postgres --hostname-strict false --http-enabled true --import-realm 
      --log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO
    depends_on:
      postgres:
        condition: service_healthy

  fuseki:
    container_name: "fuseki"
    build:
      context: '../fc-fuseki-server/'
      dockerfile: Dockerfile
    networks:
      - "gaia-x"
    restart: always
    volumes:
      - fusekidata:/fuseki_data/
    #ports:
    #  - "3330:3330"

  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always
    command: --js --sd /data -p 4222 -m 8222
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/healthz || exit 1
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks: 
      - "gaia-x"
      
  server:
    container_name: "fc-server"
#    image: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/catalogue/fc-service-server:2.0.0
    build:
      context: "${FC_SERVICE_SERVER_DOCKER_CONTEXT}"
      dockerfile: Dockerfile
      target: "${FC_SERVICE_SERVER_DOCKER_TARGET}"
    environment:
      KEYCLOAK_CREDENTIALS_SECRET: "${FC_CLIENT_SECRET}"
      SPRING_DATASOURCE_URL: "${DB_URL}"
      GRAPHSTORE_URI: "${GRAPH_STORE_URI}"
      GRAPHSTORE_USER: "${GRAPH_STORE_USER}"
      GRAPHSTORE_PASSWORD: "${GRAPH_STORE_PASSWORD}"
      PUBLISHER_IMPL: nats
      PUBLISHER_URL: ${NATS_URL}
      SUBSCRIBER_IMPL: none
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:127.0.0.1"
    restart: always #unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
      fuseki:
        condition: service_healthy
        
  portal:
    container_name: "demo-portal"
#    image: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/catalogue/fc-demo-portal:2.0.0
    build:
      context: "${FC_DEMO_PORTAL_DOCKER_CONTEXT}"
      dockerfile: Dockerfile
      target: "${FC_DEMO_PORTAL_DOCKER_TARGET}"
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FC_CLIENT_OIDC_CLIENT_SECRET: "${FC_CLIENT_SECRET}"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://key-server:8080/realms/gaia-x
      FEDERATED_CATALOGUE_BASE_URI: http://fc-server:8081
    ports:
      - "8088:8088"
    networks:
      - "gaia-x"
    extra_hosts:
      - "key-server:host-gateway"
      - "localhost:host-gateway"
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy

networks:
  gaia-x:
    driver: "bridge"

volumes:
  fusekidata:
    driver: "local"
