apiVersion: v1
kind: Service
metadata:
  name: fedcat-postgres
  labels:
    app: fedcat-postgres
  namespace: fedcat
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: fedcat-postgres