name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild-service:
    uses: eclipse-xfsc/dev-ops/.github/workflows/docker-maven.yml@main
    secrets: inherit
    with:
      repo_name: fc-service-server
      java_version: '21'
      deploy_mode: 'jib'
    
  dockerbuild-portal:
    uses: eclipse-xfsc/dev-ops/.github/workflows/docker-maven.yml@main
    secrets: inherit
    with:
      repo_name: fc-demo-portal
      java_version: '21'
      deploy_mode: 'jib'
      folder: ./fc-demo-portal
      harbor_config: ../harbor.config
  helm:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main
    secrets: inherit
    with:
      buildContext:  "deployment/helm/fc-service"
